comentarios_pisos = [
    "Ubicado cerca de todos los servicios y transporte.",
    "Piso moderno ideal para parejas o profesionales.",
    "Muy luminoso y con excelente distribución.",
    "Vecindario tranquilo y bien conectado.",
    "Espacios optimizados y funcionales.",
    "Recién reformado, listo para entrar a vivir.",
    "Perfecto como primera vivienda.",
    "Excelente inversión en zona creciente.",
    "Cercano a parques, colegios y supermercados.",
    "Balcón con vistas despejadas y buena orientación.",
    "Piso moderno en pleno centro de la ciudad, con todas las comodidades.",
    "Ideal para quienes buscan comodidad y cercanía al transporte público.",
    "Perfecto para parejas o solteros que desean vivir en una zona vibrante.",
    "Piso con excelente distribución, cómodo y lleno de luz natural.",
    "Ubicado en una zona tranquila pero cerca de todo lo necesario.",
    "Cercano a colegios, comercios y parques, ideal para familias pequeñas.",
    "Piso reformado con acabados de alta calidad, listo para mudarse.",
    "Con balcón que ofrece vistas panorámicas de la ciudad.",
    "Una excelente opción para quienes valoran la ubicación y el acceso rápido a servicios.",
    "Comodidad, diseño y funcionalidad en un solo espacio.",
    "Piso acogedor y bien ubicado, ideal para disfrutar de la vida urbana.",
    "Cerca de restaurantes, cafeterías y centros comerciales, lo tiene todo.",
    "Excelente oportunidad para invertir en un piso de una ubicación privilegiada.",
    "Con aire acondicionado y calefacción central para una mayor comodidad durante todo el año.",
    "Amplio salón y cocina independiente, perfecto para tu día a día.",
    "Piso luminoso en una planta alta, ideal para disfrutar de vistas despejadas.",
    "El lugar perfecto para vivir cerca de todo lo que necesitas sin perder la tranquilidad.",
    "Piso moderno con espacios funcionales, ideal para personas con estilo de vida activo.",
    "Ubicación estratégica, cerca de las mejores conexiones de transporte público.",
    "Piso con excelente distribución que maximiza el espacio, con grandes ventanales que aportan luz."
]

comentarios_casas = [
    "Perfecta para familias que buscan espacio y tranquilidad.",
    "El jardín es ideal para disfrutar al aire libre.",
    "Casa luminosa con espacios abiertos y cómodos.",
    "La piscina es un lujo para los días de verano.",
    "Diseño moderno y funcional en zona residencial.",
    "Ambiente seguro y rodeado de naturaleza.",
    "Gran patio ideal para mascotas o reuniones familiares.",
    "Zona muy tranquila y con buena conexión a la ciudad.",
    "Perfecta para quienes valoran la privacidad.",
    "Amplio terreno con muchas posibilidades de uso.",
    "Ideal para quienes buscan privacidad y espacios amplios.",
    "Casa con excelentes acabados y distribución en cada habitación.",
    "Perfecta para disfrutar de un jardín privado y amplias terrazas.",
    "Casa familiar en un barrio tranquilo y con buena seguridad.",
    "Gran capacidad para recibir visitas y organizar reuniones familiares.",
    "Vivienda de gran confort y ubicación estratégica cerca de zonas verdes.",
    "Moderna, espaciosa y lista para mudarse. ¡No te la pierdas!",
    "Con piscina, jardín y una gran terraza para los días soleados.",
    "Construcción reciente con todas las comodidades para tu familia.",
    "Un lugar tranquilo y rodeado de naturaleza, ideal para descansar.",
    "El hogar perfecto para disfrutar de la tranquilidad y privacidad.",
    "Espacios abiertos que permiten una excelente ventilación natural.",
    "Casa con amplios ventanales y mucha luz natural.",
    "Entorno familiar, ideal para niños y mascotas.",
    "Cerca de colegios, supermercados y transporte público.",
    "Un hogar con un diseño único que se adapta a todas tus necesidades.",
    "Con una terraza amplia perfecta para disfrutar del buen clima.",
    "Casa con vistas espectaculares, ideal para relajarse.",
    "Vivienda con cocina de diseño y amplios espacios para disfrutar.",
    "Una casa que lo tiene todo, ¡disfruta del lujo y la comodidad!"
]
